version: 2.1

commands:
  dependencies:
    description: 'Load dependency cache, get dependencies and update cache'
    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

executors:
  node:
    docker:
      - image: circleci/node:10.15.3

jobs:
  security_audit:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: yarn audit
  lint_css-framework:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p packages/css-framework/test-results/stylelint
      - run: yarn --cwd packages/css-framework --silent stylelint --custom-formatter '../../node_modules/stylelint-junit-formatter/index.js' ./index.scss > packages/css-framework/test-results/stylelint/results.xml
      - store_test_results:
          path: packages/css-framework/test-results/stylelint/test-results
      - store_artifacts:
          path: packages/css-framework/test-results/stylelint/test-results
  lint_react-component-library:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p packages/react-component-library/test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/react-component-results.xml
          command: yarn --cwd packages/react-component-library eslint -f ../../node_modules/eslint-junit/index.js ./src
      - store_test_results:
          path: packages/react-component-library/test-results
      - store_artifacts:
          path: packages/react-component-library/test-results
  lint_storybook-react-input-state:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p packages/storybook-react-input-state/test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/storybook-react-input-state-results.xml
          command: yarn --cwd packages/storybook-react-input-state eslint -f ../../node_modules/eslint-junit/index.js ./src
      - store_test_results:
          path: packages/storybook-react-input-state/test-results
      - store_artifacts:
          path: packages/storybook-react-input-state/test-results
  lint_vue-component-library:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p packages/vue-component-library/test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/vue-component-results.xml
          command: yarn --cwd packages/vue-component-library eslint -f ../../node_modules/eslint-junit/index.js ./src
      - store_test_results:
          path: packages/vue-component-library/test-results
      - store_artifacts:
          path: packages/vue-component-library/test-results
  test_react-component-library:
    executor: node
    steps:
      - checkout
      - dependencies
      - run:
          name: Jest
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/react-component-results.xml
          command: yarn --cwd packages/react-component-library jest --ci --silent --no-cache --reporters=default --reporters=jest-junit
      - store_test_results:
          path: packages/react-component-library/test-results
      - store_artifacts:
          path: packages/react-component-library/test-results
  test_storybook-react-input-state:
    executor: node
    steps:
      - checkout
      - dependencies
      - run:
          name: Jest
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/storybook-react-input-state-results.xml
          command: yarn --cwd packages/storybook-react-input-state jest --ci --silent --no-cache --reporters=default --reporters=jest-junit
      - store_test_results:
          path: packages/storybook-react-input-state/test-results
      - store_artifacts:
          path: packages/storybook-react-input-state/test-results
  test_vue-component-library:
    executor: node
    steps:
      - checkout
      - dependencies
      - run:
          name: Jest
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/vue-component-results.xml
          command: yarn --cwd packages/vue-component-library jest --ci --silent --no-cache --reporters=default --reporters=jest-junit
      - store_test_results:
          path: packages/vue-component-library/test-results
      - store_artifacts:
          path: packages/vue-component-library/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - security_audit
      - lint_css-framework
      - lint_react-component-library
      - lint_storybook-react-input-state
      - lint_vue-component-library
      - test_react-component-library:
          requires:
            - lint_react-component-library
      - test_storybook-react-input-state:
          requires:
            - lint_storybook-react-input-state
      - test_vue-component-library:
          requires:
            - lint_vue-component-library
