defaults: &defaults
  docker:
    - image: circleci/node:10.15.2
  working_directory: ~/repo

version: 2

jobs:
  build:
    <<: *defaults
    environment:
      NODE_ENV: development
    steps:
      - checkout

      - run:
          name: Install
          command: yarn install

      - run:
          name: Lint
          command: yarn run lint

      - run:
          name: Run Tests
          command: yarn run test:ci

      - store_test_results:
          path: test-results
  build-react-storybook:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build storybook
          command: |
            cd packages/react-component-library
            yarn install
            yarn run build-storybook-prod
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - packages/react-component-library/public
  deploy-react-storybook:
    <<: *defaults
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install Firebase tools
          command: cd packages/react-component-library && yarn add firebase-tools
      - run:
          name: Deploy to Firebase
          command: cd packages/react-component-library && ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_SB_REACT
  build-vue-storybook:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Build storybook
          command: |
            cd packages/vue-component-library
            yarn install
            yarn run build-storybook-prod
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - node_modules
            - .static_storybook
deploy-vue-storybook:
    <<: *defaults
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_SB_VUE
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-react-storybook
      - deploy-react-storybook:
          requires:
            - build-react-storybook
          filters:
            branches:
              only: feature/sb-deploy
      # Vue not ready yet 
      # - build-vue-storybook
      # - deploy-vue-storybook:
      #     requires:
      #       - build-vue-storybook
      #     filters:
      #       branches:
      #         only: master