version: 2.1

commands:
  dependencies:
    description: 'Load dependency cache, get dependencies and update cache'
    steps:
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}

executors:
  node:
    docker:
      - image: circleci/node:10.15.3

jobs:
  lint_css-framework:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p test-results/stylelint
      - run: yarn --silent stylelint --custom-formatter './node_modules/stylelint-junit-formatter/index.js' ./packages/css-framework/index.scss > test-results/stylelint/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  lint_html-storybook:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/html-storybook-results.xml
          command: yarn eslint -f ./node_modules/eslint-junit/index.js packages/html-storybook/src
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  lint_react-component-library:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/react-component-results.xml
          command: yarn eslint -f ./node_modules/eslint-junit/index.js packages/react-component-library/src
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  lint_storybook-react-input-state:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/storybook-react-input-state-results.xml
          command: yarn eslint -f ./node_modules/eslint-junit/index.js packages/storybook-react-input-state/src
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  lint_vue-component-library:
    executor: node
    steps:
      - checkout
      - dependencies
      - run: mkdir -p test-results/eslint
      - run:
          name: Lint
          environment:
            ESLINT_JUNIT_OUTPUT: test-results/eslint/vue-component-results.xml
          command: yarn eslint -f ./node_modules/eslint-junit/index.js packages/vue-component-library/src
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  lint:
    jobs:
      - lint_css-framework
      - lint_html-storybook
      - lint_react-component-library
      - lint_storybook-react-input-state
      - lint_vue-component-library
