version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "m7kvqbe1"
      - "thyhjwb6"

    default_labels:
      - "devops"
      - "automation"
