name: NPM Smoke Test
env:
  LOCAL_REGISTRY: "http://localhost:4873"

on:
  pull_request:


jobs:
     NPM_Smoketest:
      runs-on: ubuntu-latest

      steps:
        - name: Git clone repository
          uses: actions/checkout@v2
          with:
            path: main


        - name: Install Verdaccio
          run: |
            sudo npm install -g verdaccio
            sudo npm install -g verdaccio-auth-memory
            sudo npm install -g verdaccio-memory
            sudo npm install -g npm-auth-to-token


        - name: Configure Verdaccio
          run: |
            cat <<EOF >config.yaml
            auth:
              auth-memory:
                users:
            store:
              memory:
                limit: 10000
            uplinks:
               npmjs:
                url: https://registry.yarnpkg.com
            packages:
              '@*/*':
                access: \$all
                publish: \$all
                proxy: npmjs
              '**':
                access: \$all
                publish: \$all
                proxy: npmjs
            middlewares:
              audit:
                enabled: true
            max_body_size: 500mb
            logs:
             - {type: stdout, format: pretty, level: trace}
            server:
              keepAliveTimeout: 0
            EOF

            tmp_registry_log=`mktemp`
            mkdir -p .config/verdaccio
            cp --verbose config.yaml .config/verdaccio/config.yaml
            nohup verdaccio --config .config/verdaccio/config.yaml &>$tmp_registry_log &


        - name: Publish packages
          run: |
            cd main
            yarn install
            npm publish --registry ${{env.LOCAL_REGISTRY}} packages/css-framework
            npm publish --registry ${{env.LOCAL_REGISTRY}} packages/eslint-config-react
            npm publish --registry ${{env.LOCAL_REGISTRY}} packages/fonts
            npm publish --registry ${{env.LOCAL_REGISTRY}} packages/icon-library
            npm publish --registry ${{env.LOCAL_REGISTRY}} packages/react-component-library
            npm publish --registry ${{env.LOCAL_REGISTRY}} packages/cra-template-royalnavy


        - name: Checkout test app
          uses: actions/checkout@v2
          with:
            repository: Royal-Navy/coffee.git
            Path: coffee
            ref: master


        - name: Build test app
          run: |
            cd coffee
            yarn install
            npm ls @royalnavy/react-component-library
            yarn config set registry ${{env.LOCAL_REGISTRY}}
            yarn add @royalnavy/css-framework
            yarn add @royalnavy/icon-library
            yarn add @royalnavy/react-component-library
            npm ls @royalnavy/react-component-library


        - name: Run test app
          run: |
            cd coffee
            yarn build


        - name: Install create-react-app
          run: |
            sudo yarn global add create-react-app --registry ${{env.LOCAL_REGISTRY}}


        - name: Configure boilerplate app
          run: |
            cat main/packages/cra-template-royalnavy/template.json
            VERSION="$(grep version main/packages/cra-template-royalnavy/package.json | awk -F: '{print $2}')"
            sed -i  "s/\"latest\",/$VERSION/" main/packages/cra-template-royalnavy/template.json


        - name: Create boilerplate app
          run: |
            cat main/packages/cra-template-royalnavy/template.json
            yarn config set registry ${{env.LOCAL_REGISTRY}}
            yarn add @royalnavy/css-framework
            yarn add @royalnavy/fonts
            yarn add @royalnavy/icon-library
            yarn add @royalnavy/react-component-library
            yarn add @royalnavy/eslint-config-react
            create-react-app my-app --template file:../design-system/main/packages/cra-template-royalnavy/


        - name: Build boilerplate app
          run: |
            cd my-app
            grep version node_modules/@royalnavy/**/package.json
            echo "SKIP_PREFLIGHT_CHECK=true" > .env  #workaround for eslint CRA version issue
            yarn build


