name: Project Automation - move issues

on:
  issues:
    types: [labeled]

jobs:
  Move_labelled_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Move small/med labeled issues to Candidates column
      uses: Royal-Navy/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.GHA_ISSUES_TOKEN }}"
        project-url: "https://github.com/Royal-Navy/design-system/projects/6"
        column-name: "Candidates for Ready"
        label-name: "Small,Medium"
        columns-to-ignore: "Ready,Doing,Needs Review,Done"
