name: Update epics
on:
  issues:
    types: [opened, edited, closed, reopened, deleted]
jobs:
  epics:
    runs-on: ubuntu-latest
    name: Update epic issues
    steps:
      - name: Run epics action
        uses: Royal-Navy/epics-action@v1
        with:
          github-token: ${{ secrets.GHA_ISSUES_TOKEN }}
          epic-label-name: 'Type: Epic'
